kind: "BuildConfig"
apiVersion: "v1"
metadata:
  name: "envvar-test"
spec:
  runPolicy: "Parallel"
  strategy:
    type: "Docker"
  source:
    git:
      ref: master
      uri: "https://github.com/dwminer/openshift-envvar-test.git"
    type: Git
  output:
    to:
      kind: "ImageStream"
      name: "envvar-test"
